services:
  postgres:
    image: postgres:16
    container_name: mis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mis_user
      POSTGRES_PASSWORD: mis_password
      POSTGRES_DB: mis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: